data_service:
  host: "mira-data-service-server"  # Docker 网络中使用服务名
  port: 9090

mock_services:
  gateway:
    host: "mira-gateway-mock"  # Docker 网络中使用服务名
    port: 8080
  ida:
    host: "ida-access-service-mock"  # Docker 网络中使用服务名
    port: 9091

databases:
  - name: "mysql_test"
    type: "mysql"
    host: "mysql-test"  # Docker 网络中使用容器名（mysql-test）
    port: 3306
    user: "root"
    password: "password"
    database: "test_db"
  
  - name: "kingbase_test"
    type: "kingbase"
    host: "localhost"
    port: 54321
    user: "system"
    password: "password"
    database: "test_db"
  
  - name: "gbase_test"
    type: "gbase"
    host: "localhost"
    port: 5258
    user: "gbase"
    password: "password"
    database: "test_db"

  - name: "vastbase_test"
    type: "vastbase"
    host: "localhost"
    port: 5432
    user: "vastbase"
    password: "password"
    database: "test_db"

minio:
  endpoint: "minio:9000"  # Docker 网络中使用服务名
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "test-bucket"

