oss:
  type: "minio"
  host: "minio"
  port: 9000
  access_key: "minioadmin"
  secret_key: "minioadmin"

dbms:
  type: "mysql"
  params: "parseTime=true&loc=Local"
  host: "mysql"
  port: 3306
  user: "root"
  password: "root123456"
  db: "mira_db"
  dsn: "root:root123456@tcp(mysql:3306)/mira_db?parseTime=true&loc=Local"
  max_open_conns: 10
  max_idle_conns: 5

http:
  port: 8080
  data_server: "http://localhost:8080"

spark:
  account_name: "default-account"
  namespace: "default"
  upload_path: "/path/to/upload"
  image_name: "your-spark-image"
  image_tag: "latest"
  master: "local[*]"
  event_log_enable: true
  event_log_dir: "file:///path/to/eventlog"
  clean_interval: 3600
  bucket_name: "your-bucket-name"
  retention_days: 7
  log_retention_days: 14
  data_retention_days: 30

log:
  level: "info"

clean_table:
  clean_enable: true
  retention_days: 7
  interval: 24

common:
  port: 9090

doris:
  address: "doris-fe"
  port: 9030
  user: "root"
  password: ""
  db: ""
  batch_insert_size: 1000
  max_open_conns: 10
  max_idle_conns: 5
  max_life_time: 60
  max_idle_time: 30
  query_timeout: 1800
  import_batch_size: 10000
  import_max_retry: 3
  s3_export_max_file_size: "1GB"
  s3_export_request_timeout: 300
  s3_export_connection_timeout: 60
  s3_export_connection_maximum: 10
